name: 'Action Log Analyzer'
description: 'CI intelligence for every run — timing, test results, root cause analysis, annotations, retry awareness, and full build context for both successes and failures.'
author: 'Sathish'

branding:
  icon: 'search'
  color: 'red'

inputs:
  github-token:
    description: 'GitHub token for posting PR comments'
    required: true
    default: ${{ github.token }}
  post-comment:
    description: 'Post analysis as a PR comment'
    required: false
    default: 'true'
  post-summary:
    description: 'Post analysis as a job summary'
    required: false
    default: 'true'
  failed-job-name:
    description: 'Name of the failed job to analyze (optional)'
    required: false
    default: ''
  remote-patterns-url:
    description: 'URL to fetch additional community patterns from'
    required: false
    default: ''

outputs:
  root-cause:
    description: 'Plain-English root cause of the failure'
  failed-step:
    description: 'The step that caused the failure'
  suggestion:
    description: 'Suggested fix for the failure'
  matched-pattern:
    description: 'ID of the pattern that matched (or none)'
  category:
    description: 'Category of the failure'
  warning-count:
    description: 'Number of warnings detected in the job logs'
  build-params:
    description: 'JSON array of detected build parameters [{key, value, source}]'
  git-refs:
    description: 'JSON array of detected repositories, actions, and tags [{repo, ref, type}]'
  total-duration:
    description: 'Total job duration as human-readable string (e.g. "2m 30s")'
  slowest-step:
    description: 'Name of the slowest step in the job'
  test-summary:
    description: 'JSON object with test results {framework, passed, failed, skipped, total, failedTests}'
  run-attempt:
    description: 'Current run attempt number (1 for first run, higher for retries)'
  run-number:
    description: 'Workflow run number'
  trigger-event:
    description: 'Event that triggered the workflow (push, pull_request, schedule, etc.)'

runs:
  using: 'node20'
  main: 'dist/index.js'
